# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_number', models.CharField(help_text='Candidate/admission number, unique within the school.', max_length=40)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_phone_2', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='schools.school')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['school', 'candidate_number'], name='candidates__school__12b223_idx'), models.Index(fields=['school', 'status'], name='candidates__school__27b7b6_idx'), models.Index(fields=['last_name', 'first_name'], name='candidates__last_na_35ea62_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'candidate_number'), name='unique_candidate_number_per_school')],
            },
        ),
    ]
