# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemes', to='schools.school')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_pass', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='grading.gradingscheme')),
            ],
            options={
                'ordering': ('-min_percentage',),
            },
        ),
        migrations.CreateModel(
            name='DivisionBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('min_points', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_points', models.DecimalField(decimal_places=1, max_digits=5)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_bands', to='grading.gradingscheme')),
            ],
            options={
                'ordering': ('min_points',),
            },
        ),
        migrations.AddConstraint(
            model_name='gradingscheme',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_scheme_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='gradingscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('school',), name='unique_default_scheme_per_school'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(fields=('scheme', 'grade'), name='unique_grade_per_scheme'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.CheckConstraint(condition=models.Q(('min_percentage__gte', 0), ('max_percentage__lte', 100), ('min_percentage__lt', models.F('max_percentage'))), name='valid_grade_band_range'),
        ),
        migrations.AddConstraint(
            model_name='divisionband',
            constraint=models.UniqueConstraint(fields=('scheme', 'name'), name='unique_division_per_scheme'),
        ),
        migrations.AddConstraint(
            model_name='divisionband',
            constraint=models.CheckConstraint(condition=models.Q(('min_points__lte', models.F('max_points'))), name='valid_division_range'),
        ),
    ]
