# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('examinations', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENTERED', 'Entered'), ('ABSENT', 'Absent'), ('EXEMPT', 'Exempt'), ('MISSING', 'Missing'), ('INVALID', 'Invalid')], default='PENDING', max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.examcomponent')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('exam_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='enrollment.examinationcandidate')),
                ('school', models.ForeignKey(help_text='Denormalized candidate school for scoping.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='MarkChangeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('CLEARED', 'Cleared'), ('STATUS_CHANGE', 'Status Change'), ('CORRECTION', 'Correction')], max_length=15)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('old_status', models.CharField(blank=True, max_length=15)),
                ('new_status', models.CharField(blank=True, max_length=15)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='examinations.examcomponent')),
                ('exam_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollment.examinationcandidate')),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='marks.mark')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MarkComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('SUBJECT', 'Subject'), ('EXAMINATION', 'Examination')], default='CANDIDATE', max_length=15)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='enrollment.examinationcandidate')),
                ('exam_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='examinations.examsubject')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='examinations.examination')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['exam_candidate'], name='marks_mark_exam_ca_50f4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['component'], name='marks_mark_compone_5ef26b_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'component'], name='marks_mark_school__601a56_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['exam_candidate', 'status'], name='marks_mark_exam_ca_ab8759_idx'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('exam_candidate', 'component'), name='unique_mark_per_candidate_component'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__isnull', True), _connector='OR'), name='mark_value_non_negative'),
        ),
        migrations.AddIndex(
            model_name='markchangelog',
            index=models.Index(fields=['exam_candidate', 'component'], name='marks_markc_exam_ca_0da62d_idx'),
        ),
        migrations.AddIndex(
            model_name='markchangelog',
            index=models.Index(fields=['mark'], name='marks_markc_mark_id_90c636_idx'),
        ),
    ]
