# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('CANDIDATES', 'Candidates'), ('CANDIDATE_LIST', 'Candidate List'), ('MARKS', 'Marks'), ('RESULTS', 'Results'), ('ENROLLMENTS', 'Enrollments')], max_length=20)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel')], default='CSV', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
