# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_number', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('ABSENT', 'Absent'), ('DISQUALIFIED', 'Disqualified'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=15)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_enrollments', to='candidates.candidate')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('candidate_number',),
            },
        ),
    ]
