# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_lists', '0001_initial'),
        ('enrollment', '0001_initial'),
        ('examinations', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationcandidate',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='examinations.examination'),
        ),
        migrations.AddField(
            model_name='examinationcandidate',
            name='school',
            field=models.ForeignKey(help_text='Denormalized candidate school for school-level scoping and results.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_candidates', to='schools.school'),
        ),
        migrations.AddField(
            model_name='examinationcandidate',
            name='source_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_candidates', to='candidate_lists.candidatelist'),
        ),
        migrations.AddIndex(
            model_name='examinationcandidate',
            index=models.Index(fields=['examination', 'status'], name='enrollment__examina_f4f0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationcandidate',
            index=models.Index(fields=['examination', 'school'], name='enrollment__examina_ec3413_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationcandidate',
            index=models.Index(fields=['candidate', 'examination'], name='enrollment__candida_b25178_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationcandidate',
            constraint=models.UniqueConstraint(fields=('examination', 'candidate'), name='unique_candidate_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='examinationcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate_number__gt', '')), fields=('examination', 'candidate_number'), name='unique_candidate_number_per_exam'),
        ),
    ]
