# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('school', models.ForeignKey(blank=True, help_text='Null means the subject is global/shared across schools.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['school', 'status'], name='subjects_su_school__d88d9e_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'code'), name='unique_subject_code_per_school'), models.UniqueConstraint(django.db.models.functions.text.Lower('code'), condition=models.Q(('school__isnull', True)), name='unique_global_subject_code')],
            },
        ),
    ]
