# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('COMPETITION', 'Competition (1, 2, 2, 4)'), ('DENSE', 'Dense (1, 2, 2, 3)'), ('ORDINAL', 'Ordinal (1, 2, 3, 4)')], default='COMPETITION', max_length=15)),
                ('rank_by', models.CharField(choices=[('average_percentage', 'Average percentage'), ('total_score', 'Total score')], default='average_percentage', max_length=20)),
                ('include_absent', models.BooleanField(default=False, help_text='Rank absent/incomplete candidates at the bottom.')),
                ('is_default', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking_configs', to='schools.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_ranking_config_name_per_school')],
            },
        ),
    ]
