# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_lists', '0001_initial'),
        ('grading', '0001_initial'),
        ('ranking', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage weight used for WEIGHTED calculation; weights must sum to 100.', max_digits=6, null=True)),
                ('required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('pass_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('calculation_method', models.CharField(choices=[('NORMALIZED', 'Normalized to configured max'), ('WEIGHTED', 'Weighted component percentages'), ('RAW_TOTAL', 'Raw component total')], default='NORMALIZED', max_length=15)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('marks_status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked')], default='OPEN', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15)),
            ],
            options={
                'ordering': ('display_order', 'subject__name'),
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3'), ('ANNUAL', 'Annual'), ('MOCK', 'Mock'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('period', models.CharField(blank=True, help_text="Free-text period, e.g. 'March 2026'.", max_length=80)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('division_best_subjects', models.PositiveSmallIntegerField(default=0, help_text='Best-N subject count used for division points. 0 = all subjects.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('MARKS_ENTRY', 'Marks Entry'), ('UNDER_REVIEW', 'Under Review'), ('FINALIZED', 'Finalized'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_lists', models.ManyToManyField(blank=True, related_name='examinations', to='candidate_lists.candidatelist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_examinations', to=settings.AUTH_USER_MODEL)),
                ('grading_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='grading.gradingscheme')),
                ('participating_schools', models.ManyToManyField(blank=True, related_name='examination_participation', to='schools.school')),
                ('ranking_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='ranking.rankingconfiguration')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
