# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('reports', '0001_initial'),
        ('schools', '0001_initial'),
        ('sms', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='examination',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_examinations', to='schools.school'),
        ),
        migrations.AddField(
            model_name='examination',
            name='sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='sms.smstemplate'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='examinations.examination'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='examcomponent',
            name='exam_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='examinations.examsubject'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['school', 'status'], name='examination_school__55e296_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['status'], name='examination_status_0fcf47_idx'),
        ),
        migrations.AddConstraint(
            model_name='examination',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_exam_code_per_school'),
        ),
        migrations.AddIndex(
            model_name='examsubject',
            index=models.Index(fields=['examination', 'status'], name='examination_examina_c5024e_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('examination', 'subject'), name='unique_subject_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_marks__gt', 0)), name='exam_subject_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='examcomponent',
            constraint=models.UniqueConstraint(fields=('exam_subject', 'code'), name='unique_component_code_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='examcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_marks__gt', 0)), name='component_max_positive'),
        ),
    ]
