# Generated by Django 5.1.15 on 2026-10-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='public_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
