# Generated by Django 5.1.15 on 2026-10-02 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('school_code', models.CharField(max_length=30, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'ordering': ('school_name',),
                'indexes': [models.Index(fields=['status'], name='schools_sch_status_07bb06_idx'), models.Index(fields=['school_code'], name='schools_sch_school__9a801d_idx')],
            },
        ),
    ]
