# Generated by Django 5.1.15 on 2026-10-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set for examination centers administered by a parent organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='schools.school'),
        ),
    ]
