# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('CANDIDATE_RESULT', 'Candidate Result'), ('RESULT_SLIP', 'Result Slip'), ('FULL_RESULTS', 'Full Examination Results'), ('SUBJECT_RESULTS', 'Subject Results'), ('MARK_SHEET', 'Mark Sheet'), ('SCHOOL_RESULTS', 'School Results'), ('POSITION_REPORT', 'Candidate Position Report'), ('SUBJECT_POSITIONS', 'Subject Position Report'), ('SCHOOL_SUMMARY', 'School Summary'), ('EXAM_SUMMARY', 'Examination Summary'), ('GRADE_DISTRIBUTION', 'Grade Distribution'), ('PERFORMANCE_ANALYSIS', 'Performance Analysis'), ('MISSING_MARKS', 'Missing Marks Report'), ('ABSENT_CANDIDATES', 'Absent Candidates Report'), ('MARKS_COMPLETION', 'Marks Completion Report'), ('AUDIT', 'Audit Report')], max_length=30)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('CSV', 'CSV'), ('HTML', 'HTML Preview')], default='PDF', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to='examinations.examination')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['school', 'status'], name='reports_rep_school__34b1ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('report_type', models.CharField(choices=[('CANDIDATE_RESULT', 'Candidate Result'), ('RESULT_SLIP', 'Result Slip'), ('FULL_RESULTS', 'Full Examination Results'), ('SUBJECT_RESULTS', 'Subject Results'), ('MARK_SHEET', 'Mark Sheet'), ('SCHOOL_RESULTS', 'School Results'), ('POSITION_REPORT', 'Candidate Position Report'), ('SUBJECT_POSITIONS', 'Subject Position Report'), ('SCHOOL_SUMMARY', 'School Summary'), ('EXAM_SUMMARY', 'Examination Summary'), ('GRADE_DISTRIBUTION', 'Grade Distribution'), ('PERFORMANCE_ANALYSIS', 'Performance Analysis'), ('MISSING_MARKS', 'Missing Marks Report'), ('ABSENT_CANDIDATES', 'Absent Candidates Report'), ('MARKS_COMPLETION', 'Marks Completion Report'), ('AUDIT', 'Audit Report')], max_length=30)),
                ('header', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_positions', models.BooleanField(default=True)),
                ('show_division', models.BooleanField(default=True)),
                ('show_comments', models.BooleanField(default=True)),
                ('signature_labels', models.JSONField(blank=True, default=list, help_text='e.g. ["Class Teacher", "Head of School"]')),
                ('is_default', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='schools.school')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_report_template_name_per_school')],
            },
        ),
    ]
