# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cohort', models.CharField(blank=True, help_text="Optional grouping label, e.g. 'Form Four 2026'.", max_length=80)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_lists', to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CandidateListEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entries', to='candidates.candidate')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='candidate_lists.candidatelist')),
            ],
        ),
        migrations.AddField(
            model_name='candidatelist',
            name='candidates',
            field=models.ManyToManyField(related_name='list_memberships', through='candidate_lists.CandidateListEntry', to='candidates.candidate'),
        ),
        migrations.AddIndex(
            model_name='candidatelistentry',
            index=models.Index(fields=['candidate', 'list'], name='candidate_l_candida_b90985_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatelistentry',
            constraint=models.UniqueConstraint(fields=('list', 'candidate'), name='unique_candidate_per_list'),
        ),
        migrations.AddConstraint(
            model_name='candidatelist',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_candidate_list_name_per_school'),
        ),
    ]
