# Generated by Django 5.1.15 on 2026-10-02 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('CANDIDATES', 'Candidates'), ('MARKS', 'Marks')], max_length=20)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=15)),
                ('file', models.FileField(upload_to='imports/')),
                ('error_report', models.FileField(blank=True, null=True, upload_to='import_errors/')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('strict', models.BooleanField(default=True, help_text='When true any row error aborts the whole import; when false valid rows commit.')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
